### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by ErikStoupignan** [ErikStoupignan/Capstone-m2-APIs-baseapp-pokemon#16]
# Capstone Project - APIs Baseapp

**Link to our GitHub project:**
https://github.com/ErikStoupignan/Capstone-m2-APIs-baseapp-pokemon/projects/2

**In our project we are two members.**
👤 Erik Stoupignan Sanchez Beltran     **Student B**
👤 Daniel Gonzalez Sierra                     **Student A**

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Suggested changes
- [ ] [REQUIRED] Please replace the project link in the issue description with the [correct link](https://github.com/ErikStoupignan/Capstone-m2-APIs-baseapp-pokemon/projects/2)!

![image](https://user-images.githubusercontent.com/63915024/187303200-c91de3b3-4b5e-4cb6-b886-a36e828ec94c.png)

- [ ] [REQUIRED] All cards should be assigned to team members. You should see a circle with the user's avatar on each card. See the example below:

<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/63915024/187272346-3b0c1bab-649b-4031-817a-8b32d3751158.png">

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Mihndim2020** [comment]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi Team, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good job with task distribution

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
